FROM osixia/openldap:1.2.2

# should move this file to ldif/custom directory 
# feature should be in the next release
COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif